export MasterPage from './MasterPage'
export IndexPage from './IndexPage'
export LoginPage from './LoginPage'
export RegistrationPage from './RegistrationPage'
export ProfilePage from './ProfilePage'
export DashboardPage from './DashboardPage'
export AthletePage from './AthletePage'
export NotFoundPage from './NotFoundPage'